### ISSUE TITLE
Interpretation of +1 point improvement and accuracy with humans

### ISSUE THREAD

**Issue by ogencoglu** [kocmitom/MT-Thresholds#1]
Thanks for the work.

Regarding the tool: https://kocmitom.github.io/MT-Thresholds/

What does it mean to have +1 score increment having certain accuracy with humans? Wouldn't it make more sense that X score has Y human-agreement score. +1 increment from 20 to 21 is surely not the same as +1 from 80 to 81.

**Comment by zouharvi** [comment]
Hi Oguzhan, thanks for your interest! :slightly_smiling_face: 

> What does it mean to have +1 score increment having certain accuracy with humans? 

Say that MT1 has 80 BLEU score and MT2 has 81 BLEU score. Their difference is +1 BLEU score and BLEU rates MT2 higher than MT1. According to our research, the data, and the tool, humans would rate MT2 higher than MT1 only in 64% of cases.

> +1 increment from 20 to 21 is surely not the same as +1 from 80 to 81.

That's something we had a specific meeting about. And it is true, the human accuracy is likely affected by this and also many other things. We didn't include this in the main investigation yet because the analysis is not straightforward and requires careful resampling of system pairs.

> Wouldn't it make more sense that X score has Y human-agreement score.

Could you elaborate on what you mean by _human-agreement score_?

**Comment by kocmitom** [comment]
Hi Oguzhan, thats a great question. We mention in our work that it is a potential phenomena that could affect it, but we haven't investigated this issue in the paper. 

However, I did looked into it and I don't think any meaningful signal can be concluded from it (either the evaluation wasn't good, the phenomena is not in the data, or the noise of the data is stronger than the phenomena itself). 
I personally think that the effect of absolute score is likely not as strong or more likely it is not an issue for the systems that you usually evaluate.

A different question could be for artificial problems, such as going from 2 BLEU to 5 BLEU.

Or do you think there is a stark difference in regards to absolute values? Do you know about any research who investigated this topic?

**Comment by kocmitom** [comment]
This is from some evaluation on CometKiwi I was doing on this topic but it doesn't show any clear signal (it is not directly comparable with our paper as there is less system pairs). The issue is that it could be a problem with the evaluation itself as well and I wouldn't claim that the absolute value never play a role (maybe the phenomena is stronger for some metrics while not for other).

<img width="395" alt="image" src="https://github.com/kocmitom/MT-Thresholds/assets/14163064/a7f58cd9-4fd4-46e6-83a8-44a88d27e0bb">

**Comment by ogencoglu** [comment]
> Say that MT1 has 80 BLEU score and MT2 has 81 BLEU score. Their difference is +1 BLEU score and BLEU rates MT2 higher than MT1. According to our research, the data, and the tool, humans would rate MT2 higher than MT1 only in 64% of cases.

Thanks for the clarification. Makes sense. The word "accuracy" in the tool confused me. It is not like humans' assessment is ground truth (it is subjective anyway). That's why I thought human-agreement would be a better term. But it is all clear now.

Thanks again for swift reply @zouharvi @kocmitom !
