### ISSUE TITLE
Having pip installable tool

### ISSUE THREAD

**Issue by kocmitom** [kocmitom/MT-Thresholds#3]
Having a tool that can be called as:

```
import mtthresholds

accuracy = mtthresholds.accuracy(delta, metric_name)
```

Would be really helptul to disseminate the work.

**Comment by zouharvi** [comment]
Hi, created the Python tool and pushed to PyPi so that it's globally installable. You and are are listed as the authors.

I added a brief description to the README but there's also something on the PyPi page: https://pypi.org/project/mt-thresholds/

```bash
pip3 install mt-thresholds

# accuracy is 63.989%
mt-thresholds bleu 1.00

# ChrF needs 0.710 difference for the same accuracy as BLEU
mt-thresholds chrf 0.63989 --delta

# also works
mt_thresholds chrf 0.63989 --delta
```

Or use from Python:
```python3
import mt_thresholds

mt_thresholds.accuracy(1.0, "bleu") # 0.63989
mt_thresholds.delta(0.63989, "chrf") # 0.665
```


For further issues and improvements, let's open a new issue.

**Comment by kocmitom** [comment]
Awesome, thank you!
