### ISSUE TITLE
Adding new metrics into tool

### ISSUE THREAD

**Issue by kocmitom** [kocmitom/MT-Thresholds#4]
I have added new metrics into thresholds, can we make them partly hidden somehow (user needs to click a button for example)? Both in the selection list and in printed list?

**Comment by zouharvi** [comment]
Thanks for using the web-compatible format for thresholds. I implemented (0868a8b) what we talked about. The other metrics are hidden from the drop-down menu until the button is pressed, otherwise it might be hard to find the main ones there.

![image](https://github.com/kocmitom/MT-Thresholds/assets/7661193/cc18335e-02de-44f8-ae8c-61fe5be08c01)

![image](https://github.com/kocmitom/MT-Thresholds/assets/7661193/c698a38a-3282-4313-8425-f0f1199b1f85)

**Comment by zouharvi** [comment]
The new metrics have been pushed to the Python tool.

**Comment by kocmitom** [comment]
Thank you a lot, this looks great!
