### ISSUE TITLE
python package handling of negative numbers

### ISSUE THREAD

**Issue by kocmitom** [kocmitom/MT-Thresholds#5]
When running mt_thresholds.accuracy(-1.0, "bleu') it doesn't take only the absolute value, but tries to project sigmoid to negative values

**Comment by kocmitom** [comment]
Let's return:

sign(delta) * accuracy(abs(delta), metric)

**Comment by zouharvi** [comment]
> sign(delta) * accuracy(abs(delta), metric)

This would return negative percentage, such as -60%. Is that desireable? To me `accuracy(abs(delta), metric)` alone makes the most sense.

**Comment by kocmitom** [comment]
that is also a good solution to fix the bug. Negative percentage are to highlight and keep the direction of change. Plus they will draw attention.

**Comment by zouharvi** [comment]
Ok, I updated it with the abs:

Previously:
```
mt-thresholds bleu -1.0
> 24.345
```

Now
```
mt-thresholds bleu -1.0
> 63.989
```

In addition, I capped the lowest accuracy to 50% and added the percentage sign (to the cli output) so that it's clear what the quantity is.

Previously:
```
mt-thresholds bleu 0.1
> 46.299
mt-thresholds bleu 1.0
> 63.989
```

Now:
```
mt-thresholds bleu 0.1
> 50.000%
mt-thresholds bleu 1.0
> 63.989%
```

The latest version is [`0.0.4` live](https://pypi.org/project/mt-thresholds/0.0.4/).

We can think more about the negative percentages.

**Comment by kocmitom** [comment]
Thank you
